### ISSUE TITLE
Modelling the V-City grid

### ISSUE THREAD

**Issue by JherezTaylor** [Taxi-Coordinator/agent-simulation#2]
Represent the city as a system of nodes which represent intersections	 where customers are supposed	 to call a taxi. The numbers attached to edges e represent the distance in terms of kilometers between	intersections both horizontally and vertically.

**Comment by eduardo-salazar** [comment]
I was thinking on creating a web interface for this..And we can create an api that is going to be the Agents.

**Comment by eduardo-salazar** [comment]
Do you think this is good? wat do you think in this part?

**Comment by JherezTaylor** [comment]
Yea I think so, might be easier to model the movement on the web vs in Java UI as well.
